# Vite SPA -> static files behind nginx.
# VITE_* are inlined at BUILD time, so the gateway URL and anon key are build
# args, not runtime env. Changing either needs a rebuild, not a restart.
FROM node:22-alpine AS build
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .
ARG VITE_SUPABASE_URL
ARG VITE_SUPABASE_ANON_KEY
ARG VITE_EMAILJS_SERVICE_ID=""
ARG VITE_EMAILJS_PUBLIC_KEY=""
ARG VITE_EMAILJS_NEW_REQUEST_TEMPLATE_ID=""
ARG VITE_EMAILJS_REVIEWED_TEMPLATE_ID=""
ARG VITE_EMAILJS_CANCELLED_TEMPLATE_ID=""
ARG VITE_EMAILJS_SUBMITTED_TEMPLATE_ID=""
ENV VITE_SUPABASE_URL=$VITE_SUPABASE_URL \
    VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY \
    VITE_EMAILJS_SERVICE_ID=$VITE_EMAILJS_SERVICE_ID \
    VITE_EMAILJS_PUBLIC_KEY=$VITE_EMAILJS_PUBLIC_KEY \
    VITE_EMAILJS_NEW_REQUEST_TEMPLATE_ID=$VITE_EMAILJS_NEW_REQUEST_TEMPLATE_ID \
    VITE_EMAILJS_REVIEWED_TEMPLATE_ID=$VITE_EMAILJS_REVIEWED_TEMPLATE_ID \
    VITE_EMAILJS_CANCELLED_TEMPLATE_ID=$VITE_EMAILJS_CANCELLED_TEMPLATE_ID \
    VITE_EMAILJS_SUBMITTED_TEMPLATE_ID=$VITE_EMAILJS_SUBMITTED_TEMPLATE_ID
RUN npm run build

FROM nginx:1.27-alpine
COPY infra/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 8080
